parse_config:
  raw_binding_map:
    "&mm_mouse_l": "Ctrl+L"
    "&lt_to_layer_0_ime_off_esc 6 0": "IME Off"
    "&lt_ime_off_esc 7 0": "IME Off"
    "&lt_to_layer_0 3 LC(SPACE)": "IME Toggle"
    "&to_layer_0 INT_MUHENKAN": "無変換"
    "&mo 8": "Snipe"
    "&mo 9": "Fast"
    "&lt_mouse 8": "Snipe"
    "&lt_mouse 9": "Fast"
