name: "Draw Keymap"

on:
  workflow_dispatch:
  # push時に自動で実行する場合は、以下のコメントアウトを外す
  push:
    paths:
      - "config/roBa.keymap"
      - "keymap_drawer.config.yaml"
      - "config/roBa.dtsi"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@f9cf9d3677368a7fb1dc505c51b8156fafa66fe2
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message || 'Update keymap drawing' }}"
      amend_commit: false
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: "keymap_drawer.config.yaml" # config file, ignored if not exists
      output_folder: "keymap-drawer"

      destination: "artifact"

  deploy:
    needs: draw
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: keymap-drawer
          path: keymap-drawer

      - name: Deploy to keymap-drawer branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./keymap-drawer
          publish_branch: keymap-drawer
          commit_message: "Update keymap drawing"
          force_orphan: true
